version: "3.3"

services:
  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://estante:estante123@mongo:27017
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: estante
      MONGO_INITDB_ROOT_PASSWORD: estante123
    volumes:
      - mongo_data:/data/db
      - ./backend/mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo_data: