version: "3.3"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: estante
      MONGO_INITDB_ROOT_PASSWORD: estante123
    volumes:
      - mongo_data:/data/db
      - ./backend/mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo_data: